# Generated by Django 3.0.5 on 2020-04-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter dogs name', max_length=20)),
                ('description', models.TextField(help_text='Enter description for dog')),
                ('breed', models.CharField(help_text='Enter the breed of dog', max_length=50)),
                ('age', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='m', max_length=1, null=True)),
                ('disease_info', models.TextField(blank=True, help_text='Enter description for dog disease if there are some', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter organization name', max_length=50)),
                ('description', models.TextField(help_text='Enter description for organization')),
                ('address', models.CharField(help_text='Enter address of your organization', max_length=50)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=13)),
                ('email', models.EmailField(help_text='Enter email', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('personal_phone_number', models.CharField(help_text='Enter your personal phone number', max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_shelter.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_shelter.Organization'),
        ),
        migrations.AddField(
            model_name='dog',
            name='user_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
