# Generated by Django 3.0.5 on 2020-04-06 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dog_shelter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='OrganizationAdmin',
        ),
        migrations.AlterModelOptions(
            name='organizationadmin',
            options={'permissions': [('can_add_dog', 'can add dog'), ('can_change_dog', 'can change dog'),
                                     ('can_delete_dog', 'can delete dog'), ('can_view_dog', 'can view dog'),
                                     ('can_add_dog_images', 'can add dog images'),
                                     ('can_change_dog_images', 'can change dog images'),
                                     ('can_delete_dog_images', 'can delete dog images'),
                                     ('can_view_dog_images', 'can view dog images'),
                                     ('can_change_organization', 'can change organization'),
                                     ('can_view_organization', 'can view organization'),
                                     ('can_view_profile', 'can view profile'),
                                     ('can_change_profile', 'can change profile')]},
        ),
    ]
