# Generated by Django 3.0.5 on 2020-04-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dog_shelter', '0002_auto_20200406_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationadmin',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='dog_shelter.Organization'),
            preserve_default=False,
        ),
    ]
