# Generated by Django 3.0.5 on 2020-04-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dog_shelter', '0003_organizationadmin_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
