# Generated by Django 3.0.5 on 2020-04-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelter', '0004_auto_20200412_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationadmin',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_shelter.Organization'),
        ),
    ]
